### ISSUE TITLE
docker-compose.yml file?

### ISSUE THREAD

**Issue by chovy** [sickcodes/Docker-OSX#21]
Can we get an out of the box working docker-compose.yml and Dockerfile?

**Comment by sickcodes** [comment]
There’s a Dockerfile already in the repo.

I haven’t written a docker-compose.yml before, wouldn’t it be company specific?

Can you show me and example of one you think it should look like?

**Comment by sickcodes** [comment]
Have you ran the VNC version? You can detach that one, runs out of the box, no need to worry about displays.

**Comment by parasquid** [comment]
funnily enough, I wrote one just now (was searching for a way to automate the build).

``` yaml
version: '3.1'

services:
  db:
    image: sickcodes/docker-osx
    privileged: true
    environment:
      DISPLAY: ${DISPLAY:-:0.0}
    network_mode: "host"
    cap_add:
      - ALL
    volumes:
      - ./tmp/.X11-unix:/tmp/.X11-unix
```

This builds on one of the closed issues https://github.com/sickcodes/Docker-OSX/issues/1 so it includes the `cap` and the `net` portions that's not in the current readme. I'm running pop os 20.04 if that matters.
