### ISSUE TITLE
Forwarding a range of ports to QEMU

### ISSUE THREAD

**Issue by talkingdonkeyz** [sickcodes/Docker-OSX#484]
I am trying to use Newtek's video streaming protocol NDI within the macOS image. NDI randomly assigns ports between 49152 and 65535 to transmit on, and there is no way to choose or preempt which port it uses. I've tried the quick and dirty method of adding those 16383 ports to my docker-compose file, but that causes docker to timeout and crash. Is there any way I can forward a range of ports to QEMU? Any help would be massively appreciated! Thanks in advance.

Here is my docker file...

```
FROM sickcodes/docker-osx as base
USER arch
COPY --chown=arch packages/images/compressed.img /home/arch/OSX-KVM/mac_hdd_ng.img
COPY --chown=arch packages/discovery-server/ndi-config.v1.json /home/arch/app/ndi-config.v1.json

FROM node:16 as build
WORKDIR /usr/app/
COPY package.json .
COPY yarn.lock .
COPY ./controller ./controller
COPY ./packages/types ./packages/types
COPY ./ingest ./ingest
WORKDIR /usr/app/ingest
RUN yarn install
RUN yarn build

FROM node:16 as install
WORKDIR /usr/app/
COPY ingest/package.json .
RUN yarn install --production=true
COPY --from=build /usr/app/ingest/dist ./dist

FROM base as release
COPY --chown=arch --from=install /usr/app /home/arch/app
```

...and here is my docker-compose file...

```
  ingest:
    image: ingest:latest
    privileged: true
    ports:
      - "50922:10022"
    environment:
      CORES: "16"
      RAM: "16"
      SMP: "16"
      GENERATE_SPECIFIC: "true"
      DEVICE_MODEL: "iMacPro1,1"
      SERIAL: "C02FKSYQHX87"
      BOARD_SERIAL: "C02115700CDJG36JA"
      UUID: "11016BF1-C22C-443A-B3A0-265891DB94C1"
      MAC_ADDRESS: "98:DD:60:95:DE:5A"
      NOPICKER: "true"
      EXTRA: "-virtfs local,path=/home/arch/app,mount_tag=hostshare,security_model=passthrough,id=hostshare -display none"
      MASTER_PLIST_URL: "https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/custom/config-nopicker-custom.plist"
    devices:
      - "/dev/kvm"
```
