### ISSUE TITLE
Xvfb missing

### ISSUE THREAD

**Issue by dumbasPL** [sickcodes/Docker-OSX#498]
The naked image fails to start after a recent update. I believe it's the one from 5 days ago that broke it (digest: efdbec5854b5)

My stripped down compose (removed serials, networking, labels):
```yml
version: '3.8'
services:
  osx:
    image: sickcodes/docker-osx:naked
    restart: unless-stopped
    volumes:
      - /srv/osx/mac_hdd_ng.img:/image
    ports:
      - 50922:10022
      - 5999:5999
      - 3001:3001
    devices:
      - /dev/kvm
    environment:
      # vnc
      - EXTRA=-display none -vnc 0.0.0.0:99
```

Log:
```
nohup: failed to run command 'Xvfb': No such file or directory
```

might be related to #446
