### ISSUE TITLE
Failed to start image - Already started

### ISSUE THREAD

**Issue by mike-lloyd03** [sickcodes/Docker-OSX#524]
Thanks for making this. It's been working pretty well for me. However, I restarted docker last night while the container was running and now I cannot boot into the image. The image does not show up at the main screen and when I open UEFI shell, I get  the following error:

```
OCM: Failed to start image - Already running
BS: Failed to start OpenCore image - Already started
Halting on critical error
```
I'm guessing the image can't boot because it's last known state was already running. I've tried to reset the NVRAM but that didn't have an effect.

Any other ideas or is my image kaput?

docker-compose.yml:
```yaml
version: '3.3'
services:
    docker-osx:
        restart: unless-stopped
        volumes:
            - /mnt/data/mac-vm/mac_hdd_ng.img:/image
            - /tmp/.X11-unix:/tmp/.X11-unix
        devices:
            - /dev/kvm
        environment:
            - DISPLAY=${DISPLAY:-:0.0}
            - NOPICKER=true
            - GENERATE_SPECIFIC=true
            - DEVICE_MODEL="MacBookPro9,1"
            - SERIAL=xxxx
            - BOARD_SERIAL=xxxx
            - UUID=xxxx
            - MAC_ADDRESS=xxxx
            - WIDTH=1600
            - HEIGHT=900
            # - EXTRA=-display none -vnc 0.0.0.0:99,password=on
            - EXTRA=-display none -vnc 0.0.0.0:99
        ports:
            - 50922:10022
            - 5998:5999
        image: sickcodes/docker-osx:naked
```
