### ISSUE TITLE
docker-compose down

### ISSUE THREAD

**Issue by seevik2580** [sickcodes/Docker-OSX#54]
hi, i installed mac with `docker-compose.yml`:

```
version: '3.1'

services:
  osx:
    container_name: "docker-osx"
    build:
      context: .
      args:
        - SIZE=200G
        - VERSION=10.15.5
    image: sickcodes/docker-osx
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
      - RAM=8
      - SMP=4
      - CORES=4
    network_mode: "host"
    cap_add:
      - ALL
    volumes:
      - ./tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /lib/modules:/lib/modules
```

after successful install, when i made some changes inside `docker-compose.yml` i need to use `docker-compose down &&  docker-compose up` to take effect, but it will wipe all my data, and i have to install mac again. can you help me how to preserve volume with data ?

thanks <3

**Comment by seevik2580** [comment]
i think i figured out with creating new volume `docker volume create docker-osx_data`
then make some changes inside `docker-compose.yml`

```
version: '3.1'

services:
  osx:
    container_name: docker-osx
    build:
      context: .
      args:
        - SIZE=200G
        - VERSION=10.15.5
    image: sickcodes/docker-osx
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
      - RAM=8
      - SMP=4
      - CORES=4
    network_mode: "host"
    ports:.
      - "50922:10022"
    cap_add:
      - ALL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /lib/modules:/lib/modules
      - docker-osx_data:/home

volumes:
  docker-osx_data:
    external: true
```

and now i can safely use `docker-compose down` :)

**Comment by sickcodes** [comment]
Awesome work! Want to submit a PR?

**Comment by seevik2580** [comment]
i don't know how to do it unfortunately, i have just a little experience with git.
feel free to make yours.

**Comment by seevik2580** [comment]
here is the template, i made some changes to made docker-compose auto create volume if not exists yet. need to use version 3.4 instead of 3.1 because custom names for volumes was added in 3.4
```
version: '3.4'

services:
  osx:
    container_name: docker-osx
    build:
      context: .
      args:
        - SIZE=200G
        - VERSION=10.15.5
    image: sickcodes/docker-osx
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
    network_mode: "host"
    cap_add:
      - ALL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /lib/modules:/lib/modules
      - docker-osx_data:/home

volumes:
  docker-osx_data:
    name: docker-osx_data
```
