### ISSUE TITLE
Use SSH only without X11

### ISSUE THREAD

**Issue by shekohex** [sickcodes/Docker-OSX#60]
Great project, I have a use case where I need the VM with SSH only without GUI/X11 like in a CI/CD for example.
is that supported? 
also for example, if I want to use this in `Windows WSL 2` I had to install or configure X11, which in my use case isn't needed at all. is there an easier way?

**Comment by sickcodes** [comment]
Jump into the VNC folder and build that version :)

**Comment by shekohex** [comment]
I'll try that tonight :)

I'll close it now, if I needed something I'll reopen or make a new issue.

**Comment by shekohex** [comment]
Hey, it's me again, I successfully installed it in docker in windows using WSL2 with KVM Enabled Kernel, it works and I'm using it from SSH most of the time.
But, is there is a way that I could skip this screen? it requires me to open vnc and choose the correct drive in my case it is called `INTERNAL` which is macOS is installed.
I need when the container started up it choose it automatically or with timeout as we used in normal Hackintosh setup.
Here a  screenshot of what I'm talking about.
![vnc macos windows](https://user-images.githubusercontent.com/14620076/87250833-e754ee80-c467-11ea-85af-2ef8408dd907.png)

**Comment by shekohex** [comment]
I found #53  to be related to my comment above, I used [Open Core Configurator](https://mackie100projects.altervista.org/opencore-configurator/) to mount the EFI and edit the `config.plist` from #53 but seems that nothing changed, and nothing has been saved, am I missing something?

**Comment by daraul** [comment]
@shekohex did you check your stopped containers? (`docker ps -a`)

I just had to start the container with `docker start $containerName`.

**Comment by shekohex** [comment]
@daraul Hey,  I'm using a `docker-compose.yml` file
```yaml
version: '3.4'

services:
  osx:
    container_name: osx
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-osx-vnc
    privileged: true
    environment:
      - RAM=4
      - CORES=4
      - CPU=4
    ports:
      - '50922:10022'
      - '8888:5999'
    cap_add:
      - ALL
    volumes:
      - ~/.data/osx:/mnt/host

```
and I use `docker-compose start osx` or `docker-compose stop osx`
