### ISSUE TITLE
VNC Naked version does not respect GENERATE_SPECIFIC

### ISSUE THREAD

**Issue by mike-lloyd03** [sickcodes/Docker-OSX#602]
When building an image with https://github.com/sickcodes/Docker-OSX/blob/master/vnc-version/Dockerfile.nakedvnc, I am unable to get it to generate specific serials/UUIDs passed in via the environment.

```yaml
version: "3"

services:
  main:
    restart: unless-stopped
    devices:
      - /dev/kvm
    volumes:
      - /opt/docker/macvm/mac_hdd_ng_auto.img:/image
    image: docker-osx:nakedvnc
    ports:
      - 50922:10022
      - 5998:5999
    environment:
      - GENERATE_SPECIFIC=true
      - WIDTH=1600
      - HEIGHT=900
      - RAM=6
```

In my .env I have:
```
DEVICE_MODEL="MacBookPro9,1"
SERIAL=*********
BOARD_SERIAL=*****************
UUID=********-****-****-****-************
MAC_ADDRESS=**:**:**:**:**:**
```

But when I boot the machine, it is using the default serials and UUIDs. I think the problem is because the `Dockerfile` has two CMD instructions and only the second one is being executed (per [Docker docs](https://docs.docker.com/engine/reference/builder/#cmd)).

How can this Dockerfile be reworked to allow `GENERATE_SPECIFIC` to be honored?
