### ISSUE TITLE
Networking from container works perfectly, networking IN doesn't work at all

### ISSUE THREAD

**Issue by TimVanDyke** [sickcodes/Docker-OSX#687]
I have set up a docker container of Ventura on my Unraid box and have it working swimmingly (enough, honestly it runs like crap but I'm just excited it runs without bugs) 

My goal is to get my phone to sync over WiFi. I'm on the same network and used NoMachine to connect it via USB the first time. I have set it up as a trusted device. However, Finder does not see the phone when on the same network. 

Looking deeper, NoMachine actually only worked from docker container -> laptop, I could not for the life of me get laptop -> docker. I suspect it's some networking thing. I also don't see it as a "connected device" on my router screen the way I see my Windows VM listed. Also (probably not important but maybe a good hint?) the IP it gets is very different from the other IP's assigned by my router. Instead of 192.X.X.X (like literally everything else I see and have been working with) it's 10.X.X.X

I ran these steps and it did not seem to fix the issue: 
![image](https://github.com/sickcodes/Docker-OSX/assets/26557333/d32694d5-fd08-450f-8a9b-1b76fd08338d)

Any suggestions would be appreciated. I'm not a Linux noob but am a complete macOS noob AND Unraid noob and Docker noob so I know I have a lot to learn. (PS I tried to join discord and ask there and the invite link is broken)

**Comment by TimVanDyke** [comment]
UPDATE: 

I think setting my network to br0 made it visible on the network. I don't know a lot but afaik that is a custom unraid bridge for that purpose. Here's my docker compose file if anyone wants it: 

```
services:
    macos:
        container_name: 'MacOS'
        image: 'docker-osx-vnc:latest'
        privileged: true
        devices:
            - /dev/kvm
            - /dev/snd
            - /dev/null
        network_mode: br0 
        ports:
            - '8888:5999'
            - '50922:10022'
        environment:
            - 'USERNAME=user'
            - 'PASSWORD=pass'
            - 'DISPLAY=${DISPLAY:-:0.0}'
```

**Comment by TimVanDyke** [comment]
Update2: 

This did not fix the issue. However, the arch image has it's own IP. The macOS image inside does not get the IP forwarded to it.

**Comment by TimVanDyke** [comment]
Update3: 

This docker compose doesn't work either: 

I'm still stuck on 10.0.2.15 (which I see is the same as this) 

https://github.com/sickcodes/Docker-OSX/issues/51

But I don't understand what the important difference is. 

```
services:
    macos:
        container_name: 'MacOS'
        image: 'docker-osx-vnc:latest'
        privileged: true
        devices:
            - /dev/kvm
            - /dev/snd
            - /dev/null
        network_mode: br0
        # mac_address: 'C3:69:7C:16:0E:89'
        environment:
            - 'USERNAME=user'
            - 'PASSWORD=pass'
            - 'DISPLAY=${DISPLAY:-:0.0}'
```

**Comment by TimVanDyke** [comment]
Trying this now: 
```
services:
    macos:
        container_name: 'MacOS'
        image: 'docker-osx-vnc:latest'
        privileged: true
        devices:
            - /dev/kvm
            - /dev/snd
            - /dev/null
        network_mode: br0
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - '/dev:/dev'
            - '/lib/modules:/lib/modules'
            - '/var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock'
        environment:
            - 'USERNAME=user'
            - 'PASSWORD=pass'
            - 'DISPLAY=${DISPLAY:-:0.0}'
```

Special thanks to this website for translating for me: https://www.composerize.com/

Translated from 
```
docker run --privileged --net host -e "DISPLAY=${DISPLAY:-:0.0}" -e RAM=6 --cap-add=ALL -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev -v /lib/modules:/lib/modules  -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock docker-osx:latest
```
