### ISSUE TITLE
using docker-compose

### ISSUE THREAD

**Issue by vespino** [sickcodes/Docker-OSX#751]
The following command creates a container that I can use via VNC:

`docker run -i --device /dev/kvm --name=docker-osx -p 50922:10022 -p 5999:5999 -e "DISPLAY=${DISPLAY:-:0.0}" -e GENERATE_SPECIFIC=true -e DEVICE_MODEL="iMacPro1,1" -e SERIAL="C02YR6YYHX87" -e BOARD_SERIAL="C027251024NJG72UE" -e UUID="5CCB366D-9118-4C91-A00E-E5BEF3BED451" -e MAC_ADDRESS="E8:5C:2C:9F:46:2E" -e EXTRA="-display none -vnc 0.0.0.0:99,password=off" sickcodes/docker-osx:ventura`

Using composerize.com I have converted this to a docker-compose.yml file:

```
services:
    docker-osx:
        stdin_open: true
        devices:
            - /dev/kvm
        container_name: docker-osx2
        ports:
            - 50923:10022
            - 5998:5999
        environment:
            - DISPLAY=${DISPLAY:-:0.0}
            - GENERATE_SPECIFIC=true
            - DEVICE_MODEL=iMacPro1,1
            - SERIAL=C02YR6YYHX87
            - BOARD_SERIAL=C027251024NJG72UE
            - UUID=5CCB366D-9118-4C91-A00E-E5BEF3BED451
            - MAC_ADDRESS=E8:5C:2C:9F:46:2E
            - EXTRA="-display none -vnc 0.0.0.0:199,password=off"
        image: sickcodes/docker-osx:ventura
```

When running docker-compose up however it stops with the following output:

```
docker-osx2  | qemu-system-x86_64: -vnc 0.0.0.0:199,password=off": Parameter 'password' expects 'on' or 'off'
docker-osx2 exited with code 1
```

When removing the double quotes from EXTRA="-display none -vnc 0.0.0.0:199,password=off" container creation stops at:

```
docker-osx2  | alsa: Reason: No such file or directory
docker-osx2  | audio: Failed to create voice `adc'
```

At this point I can’t use it using VNC.

Any thoughts?
