### ISSUE TITLE
VNC password does not want to be saved. Saved until restarted.

### ISSUE THREAD

**Issue by arpsyapathy** [sickcodes/Docker-OSX#783]
Hi all!
I have docker-compose.yml
```
services:
    builder-mac:
        stdin_open: true
        restart: unless-stopped
        devices:
            - /dev/kvm
        image: sickcodes/docker-osx:naked
        ports:
            - 50922:10022
            - 5999:5999
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev:/dev
            - ${PWD}/mac_hdd_ng.img:/image
        environment:
            - SIZE=200G
            - RAM=8
            - DISPLAY=${DISPLAY:-:0.0}
            - EXTRA=-display none -vnc 0.0.0.0:99,password=on
            - DEVICE_MODEL=iMacPro1,1 
            - SERIAL=****************
            - BOARD_SERIAL==****************
            - UUID==****************
            - MAC_ADDRESS==****************
            - CPU=Haswell-noTSX
            - NETWORKING=vmxnet3
        networks:
          main:
            ipv4_address: 192.168.100.10
 
networks:
  main:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1
```

Everything is work, but VNC password does not want to be saved.
What i do:
1. I'm attach to a container
`docker compose attach builder-mac`
2. change pass VNC
1(qemu) change vnc password`
3. I connect with VNС client to container - Everything is ok. I'm connecting.
4. `docker compose down` and than `docker compose up -d`
5. I'm trying to connect via VNC, but it doesn't work. The password is incorrect.

I repeat everything again and I connect successfully. I reboot the container - the password is unknown.

Please tell me how to fix this? How can I force it to save the VNC password?
Thank you advanced!
